//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_36047
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car.
    /// </summary>
    // *** Start programmer edit section *** (Car CustomAttributes)

    // *** End programmer edit section *** (Car CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CarE", new string[] {
            "name as \'Name\'"})]
    [View("CarL", new string[] {
            "name as \'Name\'"})]
    public class Car : ICSSoft.STORMNET.DataObject
    {

        private string fname;

        // *** Start programmer edit section *** (Car CustomMembers)

        // *** End programmer edit section *** (Car CustomMembers)


        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (Car.name CustomAttributes)

        // *** End programmer edit section *** (Car.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (Car.name Get start)

                // *** End programmer edit section *** (Car.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (Car.name Get end)

                // *** End programmer edit section *** (Car.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.name Set start)

                // *** End programmer edit section *** (Car.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (Car.name Set end)

                // *** End programmer edit section *** (Car.name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "CarE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarE", typeof(IIS.Product_36047.Car));
                }
            }

            /// <summary>
            /// "CarL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarL", typeof(IIS.Product_36047.Car));
                }
            }
        }
    }
}

